apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-node-service
  labels:
    app: skaffold-node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-node-service
  template:
    metadata:
      labels:
        app: skaffold-node-service
    spec:
      restartPolicy: Always
      containers:
      - name: skaffold-node-service-latest
        image: skaffold-node-service:latest
        command: [ "npx", "nodemon", "--inspect", "--unhandled-rejections=strict", "src/index.js" ]
        imagePullPolicy: Never
        # enable probes when deploying to a live env
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 8443
        #     scheme: HTTPS
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /status
        #     port: 8443
        #     scheme: HTTPS
        #   initialDelaySeconds: 5
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 5
        ports:
        - containerPort: 8443
        env:
          - name: AWS_DYNAMODB_ENDPOINT
            value: "http://localstack:4566"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            value: "xxxx"
          - name: AWS_SECRET_ACCESS_KEY
            value: "xxxx"
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: AWS_S3_ENDPOINT
            value: "http://localstack:4566"
          - name: ARTWORK_BUCKET
            value: artwork