apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
    tier: aws_backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4566
    targetPort: 4566
    name: http