apiVersion: v1
kind: Service
metadata:
  name: skaffold-node-service
spec:
  selector:
    app: skaffold-node-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
    nodePort: 31110
    name: main
  - protocol: TCP
    port: 9229
    targetPort: 9229
    nodePort: 31111
    name: debug